# https://github.com/habx/devops-repo-shared-configs/blob/dev/github-settings/ts-lib-service.yml
# 2022-03-17
# last_update: 2022-07-27
_extends: devops-repo-shared-configs:github-settings/ts-lib-service.yml
