version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    # https://dependabot.com/docs/config-file/#automerged_updates
    automerged_updates:
      - match: { dependency_type: "development", update_type: "security:patch" }
      - match: { dependency_type: "production", update_type: "security:patch" }
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
